x-logging: &default-logging
  driver: json-file
  options:
    max-size: "10m"
    max-file: "3"

services:
  kavita:
    image: jvmilazz0/kavita:latest
    container_name: kavita
    restart: unless-stopped
    logging: *default-logging
    environment:
      TZ: Europe/Berlin
    volumes:
      - /mnt/synology_backup/jens/Kavita/config:/kavita/config
      - /mnt/synology_backup/jens/Kavita/books:/books
    networks:
      - homelab
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kavita.rule=Host(`books.jenskock.de`)"
      - "traefik.http.routers.kavita.entrypoints=web"
      - "traefik.http.services.kavita.loadbalancer.server.port=5000"

networks:
  homelab:
    external: true
    name: homelab
