x-logging: &default-logging
  driver: json-file
  options:
    max-size: "10m"
    max-file: "3"

services:
  books:
    image: crocodilestick/calibre-web-automated:latest
    container_name: books
    restart: unless-stopped
    logging: *default-logging
    env_file:
      - /opt/books/.env
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: Europe/Berlin
      NETWORK_SHARE_MODE: "true"
      TRUSTED_PROXY_COUNT: "2"
    volumes:
      - /opt/books/config:/config
      - /mnt/synology_backup/jens/ebooks/inbox:/cwa-book-ingest
      - /mnt/synology_backup/jens/ebooks/books/books:/calibre-library
    networks:
      - homelab
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.books.rule=Host(`books.jenskock.de`)"
      - "traefik.http.routers.books.entrypoints=web"
      - "traefik.http.services.books.loadbalancer.server.port=8083"

networks:
  homelab:
    external: true
    name: homelab
