x-logging: &default-logging
  driver: json-file
  options:
    max-size: "10m"
    max-file: "3"

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    logging: *default-logging
    env_file:
      - /opt/n8n/.env
    volumes:
      - /opt/n8n/data:/home/node/.n8n
    networks:
      - homelab
    depends_on:
      - gotenberg
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.n8n.rule=Host(`n8n.jenskock.de`)"
      - "traefik.http.routers.n8n.entrypoints=web"
      - "traefik.http.services.n8n.loadbalancer.server.port=5678"

  gotenberg:
    image: gotenberg/gotenberg:8
    container_name: n8n-gotenberg
    restart: unless-stopped
    logging: *default-logging
    command:
      - "gotenberg"
      - "--api-timeout=60s"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=^file:///tmp/.*"
    networks:
      - homelab

networks:
  homelab:
    external: true
    name: homelab
