x-logging: &default-logging
  driver: json-file
  options:
    max-size: "10m"
    max-file: "3"

services:
  homeassistant:
    image: homeassistant/home-assistant:latest
    container_name: homeassistant
    restart: unless-stopped
    logging: *default-logging
    volumes:
      - /opt/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8123:8123"
    networks:
      - homelab

  glances:
    image: nicolargo/glances:latest
    container_name: glances
    restart: unless-stopped
    logging: *default-logging
    ports:
      - "61208:61208"
    pid: "host"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/os-release:/etc/os-release:ro
    environment:
      - GLANCES_OPT=-w
    networks:
      - homelab

networks:
  homelab:
    external: true
    name: homelab
