x-logging: &default-logging
  driver: json-file
  options:
    max-size: "10m"
    max-file: "3"

services:
  homepage:
    image: ghcr.io/jenskock/homepage:dev
    container_name: homepage
    restart: unless-stopped
    logging: *default-logging
    networks:
      - homelab
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage.rule=Host(`jenskock.de`) || Host(`www.jenskock.de`)"
      - "traefik.http.routers.homepage.entrypoints=web"
      - "traefik.http.services.homepage.loadbalancer.server.port=3000"

networks:
  homelab:
    external: true
    name: homelab
